# Generated by Django 4.1.3 on 2022-12-26 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Projects')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='Project_url')),
                ('description', models.TextField(verbose_name='Desription')),
                ('issues', models.TextField(verbose_name='Issues')),
                ('solve', models.TextField(verbose_name='Solution')),
                ('time_create', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'My project',
                'verbose_name_plural': 'My projects',
                'ordering': ['-time_create', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.myproject')),
            ],
        ),
    ]
