# Generated by Django 4.1.3 on 2022-12-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproject',
            name='time_create',
            field=models.DateField(),
        ),
    ]
